### ISSUE TITLE
Zvětšit omezení délky názvu školy

### ISSUE THREAD

**Issue by Engin1980** [Filip-Krizak7/Bakalarska-Prace#4]
Registrace školy je omezena na 5-50 znaků. Budeme zapisovat krátké názvy, nebo názvy jak patří. Např. Střední průmyslová škola elektrotechniky a informatiky … je delší než 50 znaků. Lze jednoduše změnit v AddSchoolComponent.js (const validateAddSchool)

Zvýšit na 256 znaků.

**Comment by Filip-Krizak7** [comment]
změněno na 2-75
